### ISSUE TITLE
Host on github pages with refresh ability.

### ISSUE THREAD

**Issue by saksham-tiwari** [yashraut362/Daily-Schedule#7]
I can resolve this, can you assign it to me @yashraut362

**Comment by yashraut362** [comment]
this repo is just a dead side project, not maintained and not used I am making this repository private !
Please consider contributing to other projects!
Happy hacktoberfest !

**Comment by saksham-tiwari** [comment]
> this repo is just a dead side project, not maintained and not used I am making this repository private ! Please consider contributing to other projects! Happy hacktoberfest ! @saksham-tiwari

ok, sad to hear.
